"""Nullable believed

Revision ID: cfe517fbdba2
Revises: f0ff83bd9724
Create Date: 2024-01-22 17:51:53.480787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe517fbdba2'
down_revision: Union[str, None] = 'f0ff83bd9724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'publisher_publication', ['id'])
    op.alter_column('publisher_vote', 'believed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(None, 'publisher_vote', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publisher_vote', type_='unique')
    op.alter_column('publisher_vote', 'believed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'publisher_publication', type_='unique')
    # ### end Alembic commands ###
