# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - uses: actions/checkout@v3
    - name: Create env file
      run: |
        echo "${{ vars.PUBLISHER_ENV_FILE }}" > .env
    - name: Build containers
      run: |
        docker-compose up -d publisher
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        docker exec dev-verim-publisher python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        docker exec dev-verim-publisher python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    - name: Test with pytest
      run: |
        docker exec dev-verim-publisher python -m pytest tests --doctest-modules --junitxml=junit/publisher-test-results.xml --cov=. | tee publisher-test-results.txt
        docker cp dev-verim-publisher:/microservice/junit/publisher-test-results.xml .
    - name: Pytest publisher coverage comment
      id: publisherCoverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./publisher-test-results.txt
        hide-badge: false
        hide-report: false
        create-new-comment: true
        hide-comment: false
        report-only-changed-files: true
        remove-link-from-badge: true
        junitxml-path: ./publisher-test-results.xml

    # Only on develop merge!!!
    - name: Pytest publisher coverage badge
      if: ${{ github.ref == 'refs/heads/develop' }}
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 757112fa1eaaf7bee58f771e2238c394
        filename: VerimDevPublisherCoverage.json
        label: Publisher Coverage
        message: ${{ steps.publisherCoverageComment.outputs.coverage }}
        color: ${{ steps.publisherCoverageComment.outputs.color }}
        namedLogo: python
